"""
Django settings for my_tennis_club project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv # Optionnel : pour charger le .env en local


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger le fichier .env si vous êtes en local
load_dotenv(os.path.join(BASE_DIR, ".env"))


# --- CONFIGURATION SÉCURISÉE ---
# En production, récupère la clé secrète depuis l'hébergeur. En local, utilise une clé de secours.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-_0@8t30kv=#o(vsr^056w2u(n5x+dr6$&s@_@3v9m0pjytm33w')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-_0@8t30kv=#o(vsr^056w2u(n5x+dr6$&s@_@3v9m0pjytm33w'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# Ne jamais laisser DEBUG = True en production (sur Render)
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ALLOWED_HOSTS = [
#     "*",
#     # '127.0.0.1',
#     # 'localhost'
# ]
# Autoriser l'URL de votre site Render et localhost
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "members",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'my_tennis_club.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_tennis_club.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': "neondb",
#         "USER": "neondb_owner",
#         "PASSWORD": "npg_BYOjyRpq0sf1",
#         "HOST": "@ep-silent-union-ay8u7hpq-pooler.c-5.us-east-2.aws.neon.tech",
#         "PORT": "5432",
#     }
# }

# import dj_database_url

# DATABASES = {
#     'default': dj_database_url.parse(
#         "postgresql://neondb_owner:npg_BYOjyRpq0sf1@ep-silent-union-ay8u7hpq-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
#     )
# }

# import os
# import dj_database_url


# DATABASES = {
#     'default': dj_database_url.parse(
#         os.environ.get("DATABASE_URL", "postgresql://neondb_owner:npg_BYOjyRpq0sf1@ep-silent-union-ay8u7hpq-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require")
#     )
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',
        'USER': 'neondb_owner',
        'PASSWORD': 'npg_BYOjyRpq0sf1',
        'HOST': 'ep-silent-union-ay8u7hpq-pooler.c-5.us-east-2.aws.neon.tech',
        'PORT': '5432',
        'OPTIONS': {'sslmode': 'require'}
    }
}



# postgresql://neondb_owner:npg_BYOjyRpq0sf1@ep-silent-union-ay8u7hpq-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# --- CONFIGURATION DE LA BASE DE DONNÉES ---
# DATABASES = {
#     'default': dj_database_url.config(
#         # Si DATABASE_URL n'existe pas (en local), utilise SQLite par défaut pour coder hors ligne
#         default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }

CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "https://*.onrender.com").split(",")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "productionfiles"

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'mystaticfiles'
]