# services:
#   - type: web
#     name: tps-django
#     env: python
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "gunicorn my_tennis_club.wsgi:application"
#     postDeployCommand: "python manage.py migrate && python manage.py collectstatic --noinput"

services:
  - type: web
    name: tps-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_tennis_club.wsgi:application"
    postDeployCommand: "python manage.py migrate && python manage.py collectstatic --noinput"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "django-insecure-_0@8t30kv=#o(vsr^056w2u(n5x+dr6$&s@_@3v9m0pjytm33w"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "tps-django-1.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://tps-django-1.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_BYOjyRpq0sf1@ep-silent-union-ay8u7hpq-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"  # URL fournie par Neon
